- name: Hardening_Playbook
  hosts: myhosts
  tasks:
#---------------------------------------------------------------------------- 
#V-257779
#This is not a DoD system, only for example

    - name: RHEL9 must display DoD Notice
      copy:
        src: ../source_files/dod_banner_example.txt
        dest: /etc/issue
        owner: root
        group: root
        mode: 0644

#---------------------------------------------------------------------------- 
#V-257781

    - name: Graphical display manager must not be the default target on RHEL9
      ansible.builtin.command: 
        cmd: systemctl set-default multi-user.target

#---------------------------------------------------------------------------- 
#V-257782 - RHEL 9 must enable the hardware random number generator entropy gatherer service

    - name: Install rng-tools
      dnf:
        name:
          - rng-tools
        state: latest

    - name: Enable rng-tools
      shell: |
        systemctl enable --now rngd  
        systemctl start rngd
    
#---------------------------------------------------------------------------- 
#V-257783 - RHEL 9 systemd-journald service must be enabled
      
    - name: Enable systemd-journald
      shell: |
        systemctl enable --now systemd-journald
        systemctl start systemd-journald

#---------------------------------------------------------------------------- 
#V-257784 - THe systemd Ctrl-Alt-Delete brust key sequence in RHEL 9 must be disabled

    - name: Disabled Ctrl-Alt-Delete
      lineinfile:
        path: /etc/systemd/system.conf
        regexp: '^(.*)CtrlAltDelBurstAction(.*)$'
        line: 'CtrlAltDelBurstAction=none'
        backrefs: yes

#---------------------------------------------------------------------------- 
#V-257785 - The x86 Ctrl-ALt-Delete key sequence must be disabled on RHEL 9

    - name: Disable and mask ctrl-alt-delete.tart
      shell: |
        systemctl disable --now ctrl-alt-del.target
        systemctl mask --now ctrl-alt-del.target

#---------------------------------------------------------------------------- 
#V-257786 - RHEL 9 debug-shell systemd service must be disabled

    - name: Disable and mask debug-shell.service
      shell: |
        systemctl disable --now debug-shell.service
        systemctl mask --now debug-shell.service
    
#----------------------------------------------------------------------------
#V-257787 - RHEL 9 must require a boot loader superuser password
#This needs arguments to set and confirm password

    - name: Set a grub bootloader password. 
      ansible.builtin.expect:
        command: grub2-setpassword
        responses:
          (?i)Enter password: "random_password"
          (?i)Confirm password: "random_password" 

#----------------------------------------------------------------------------
#V-257788 - RHEL 9 must disable the ability of systemd to spawn an interactive boot process

    - name: Disable systemd.confirm_spawn
      ansible.builtin.command:
        cmd: grubby --update-kernel=ALL --remove-args="systemd.confirm_spawn"

#---------------------------------------------------------------------------
#V-257789 - RHEL 9 requires a unique superusers name upon booting image into single user and maintenance modes

    - name: Create a superuser account
      ansible.builtin.user:
        name: super_maint_user
        comment: This is the Maintenance Superuser account

    - name: Set superuser to super_maint_user
      lineinfile:
        path: /etc/grub.d/01_users
        regexp: '^(.*)set superusers(.*)$'
        line: 'set superusers="super_maint_user'
        backrefs: yes

    - name: Export superusers
      lineinfile:
        path: /etc/grub.d/01_users
        regexp: '^(.*)export superusers(.*)$'
        line: 'export superusers'
        backrefs: yes

    - name: Update Grubby
      ansible.builtin.command:
        cmd: grubby --update-kernel=ALL

#---------------------------------------------------------------------------
#V-257790 - RHEL 9 /boot/grub2/grub.cfg file must be group owned by root

    - name: Set root as owner as grub.cfg
      ansible.builtin.command:
        cmd: chgrp root /boot/grub2/grub.cfg

#---------------------------------------------------------------------------
