- name: RHEL9_STIG_V1R2
  hosts: myhosts
  tasks:
#---------------------------------------------------------------------------- 
#V-257779
#This is not a DoD system, only for example

    - name: RHEL9 must display DoD Notice
      copy:
        src: ../source_files/dod_banner_example.txt
        dest: /etc/issue
        owner: root
        group: root
        mode: 0644

#---------------------------------------------------------------------------- 
#V-257781

    - name: Graphical display manager must not be the default target on RHEL9
      ansible.builtin.command: 
        cmd: systemctl set-default multi-user.target

#---------------------------------------------------------------------------- 
#V-257782 - RHEL 9 must enable the hardware random number generator entropy gatherer service

    - name: Install rng-tools
      dnf:
        name:
          - rng-tools
        state: latest

    - name: Enable rng-tools
      shell: |
        systemctl enable --now rngd  
        systemctl start rngd
    
#---------------------------------------------------------------------------- 
#V-257783 - RHEL 9 systemd-journald service must be enabled
      
    - name: Enable systemd-journald
      shell: |
        systemctl enable --now systemd-journald
        systemctl start systemd-journald

#---------------------------------------------------------------------------- 
#V-257784 - THe systemd Ctrl-Alt-Delete brust key sequence in RHEL 9 must be disabled

    - name: Disabled Ctrl-Alt-Delete
      lineinfile:
        path: /etc/systemd/system.conf
        regexp: '^(.*)CtrlAltDelBurstAction(.*)$'
        line: 'CtrlAltDelBurstAction=none'
        backrefs: yes

#---------------------------------------------------------------------------- 
#V-257785 - The x86 Ctrl-ALt-Delete key sequence must be disabled on RHEL 9

    - name: Disable and mask ctrl-alt-delete.tart
      shell: |
        systemctl disable --now ctrl-alt-del.target
        systemctl mask --now ctrl-alt-del.target

#---------------------------------------------------------------------------- 
#V-257786 - RHEL 9 debug-shell systemd service must be disabled

    - name: Disable and mask debug-shell.service
      shell: |
        systemctl disable --now debug-shell.service
        systemctl mask --now debug-shell.service
    
#----------------------------------------------------------------------------
#V-257787 - RHEL 9 must require a boot loader superuser password
#This needs arguments to set and confirm password

    - name: Set a grub bootloader password. 
      ansible.builtin.expect:
        command: grub2-setpassword
        responses:
          (?i)Enter password: "random_password"
          (?i)Confirm password: "random_password" 

#----------------------------------------------------------------------------
#V-257788 - RHEL 9 must disable the ability of systemd to spawn an interactive boot process

    - name: Disable systemd.confirm_spawn
      ansible.builtin.command:
        cmd: grubby --update-kernel=ALL --remove-args="systemd.confirm_spawn"

#---------------------------------------------------------------------------
#V-257789 - RHEL 9 requires a unique superusers name upon booting image into single user and maintenance modes

    - name: Create a superuser account
      ansible.builtin.user:
        name: super_maint_user
        comment: This is the Maintenance Superuser account

    - name: Set superuser to super_maint_user
      lineinfile:
        path: /etc/grub.d/01_users
        regexp: '^(.*)set superusers(.*)$'
        line: 'set superusers="super_maint_user'
        backrefs: yes

    - name: Export superusers
      lineinfile:
        path: /etc/grub.d/01_users
        regexp: '^(.*)export superusers(.*)$'
        line: 'export superusers'
        backrefs: yes

    - name: Update Grubby
      ansible.builtin.command:
        cmd: grubby --update-kernel=ALL

#---------------------------------------------------------------------------
#V-257790 - RHEL 9 /boot/grub2/grub.cfg file must be group owned by root

    - name: Set root as group owner of grub.cfg
      ansible.builtin.command:
        cmd: chgrp root /boot/grub2/grub.cfg

#---------------------------------------------------------------------------
#V-257791 - RHEL 9 /boot/grub2/grub.cfg

    - name: Set root as owner of grub.cfg
      ansible.builtin.command:
        cmd: chown root /boot/grub2/grub.cfg

#---------------------------------------------------------------------------
#V-257792 - RHEL 9 Must disable virtual system calls

    - name: Copy Grubby script locally
      copy:
        src: ../source_files/grubby_harden.py
        dest: /root
        owner: root
        group: root
        mode: 0700

    - name: Run grubby_harden.py to add vsyscall=none
      shell: |
        grubby --update-kernel=ALL --args="vsyscall=none"
        python /root/grubby_harden.py vsyscall=none

#---------------------------------------------------------------------------
#V-257793 - RHEL 9 Must clear the page allocator to prevent use-after-free attacks

    - name: Run grubby_harden.py to add page_poison=1
      shell: |
        grubby --update-kernel=ALL --args="page_poison=1"
        python /root/grubby_harden.py page_poison=1

#---------------------------------------------------------------------------
#V-257794 - RHEL 9 Must clear SLUB/SLAB Objects to prevent use-after-free attacks

    - name: Run grubby_harden.py to add slub_debug=P
      shell: |
        grubby --update-kernel=ALL --args="slub_debug=P"
        python /root/grubby_harden.py slub_debug=P

#---------------------------------------------------------------------------
#V-257795 - RHEL 9 Must enable mitigations against processor-based vulnerabilities
    
    - name: Run grubby_harden.py to add pti=on
      shell: |
        grubby --update-kernel=ALL --args="pti=on"
        python /root/grubby_harden.py pti=on

#---------------------------------------------------------------------------
#V-257796 - RHEL 9 Must enable auditing of processes that start prior to the audit daemon    

    - name: Run grubby_harden.py to add audit=1
      shell: |
        grubby --update-kernel=ALL --args="audit=1"
        python /root/grubby_harden.py audit=1

#---------------------------------------------------------------------------
#V-257797 - RHEL 9 Must restrict access to the kernel message buffer    

    - name: Copy sysctl.d script locally
      copy:
        src: ../source_files/sysctl_d_harden.py
        dest: /root
        owner: root
        group: root
        mode: 0700

    - name: Run sysctl_d_harden.py to add kernel.dmesg_restrict=1
      shell: |
        python /root/sysctl_d_harden.py kernel.dmesg_restrict=1
        sysctl --system

#---------------------------------------------------------------------------
#V-257798 - RHEL 9 Must prevent kernel profiling by nonprivileged users

    - name: Run sysctl_d_harden.py to add kernel.perf_event_paranoid=2
      shell: |
        python /root/sysctl_d_harden.py kernel.perf_event_paranoid=2
        sysctl --system

#---------------------------------------------------------------------------
#V-257799 - RHEL 9 Must prevent the loading of a new kernel for later execution    

    - name: Run sysctl_d_harden.py to add kernel.kexec_load_disabled=1
      shell: |
        python /root/sysctl_d_harden.py kernel.kexec_load_disabled=1
        sysctl --system

#---------------------------------------------------------------------------
#v-257800 - RHEL 9 Must restrict exposed kernel pointer addresses access

    - name: Run sysctl_d_harden.py to add kernel.kptr_restrict=1
      shell: |
        python /root/sysctl_d_harden.py kernel.kptr_restrict=1
        sysctl --system

#---------------------------------------------------------------------------
#V-257801 - RHEL 9 Must enable kernel parameters to enforce discretionary access control on hardlinks

    - name: Run sysctl_d_harden.py to add fs.protected_hardlinks=1
      shell: |
        python /root/sysctl_d_harden.py fs.protected_hardlinks=1
        sysctl --system

#---------------------------------------------------------------------------
#V-257802 - RHEL 9 Must enable kernel parameters to enforce discretionary access control on symlinks

    - name: Run sysctl_d_harden.py to add fs.protected_symlinks=1
      shell: |
        python /root/sysctl_d_harden.py fs.protected_symlinks=1
        sysctl --system

#---------------------------------------------------------------------------
#V-257803 - RHEL 9 Must disable the kernel.core_pattern

    - name: Run sysctl_d_harden.py to add "kernel.core_pattern=|/bin/false"
      shell: |
        python /root/sysctl_d_harden.py kernel.core_pattern=\|/bin/false
        sysctl --system

#---------------------------------------------------------------------------
#V-257804 - RHEL 9 Must be configured to disable the Asynchronous Transfer Mode kernel module

    - name: Copy modprobe_modules script locally
      copy:
        src: ../source_files/modprobe_modules.sh
        dest: /root
        owner: root
        group: root
        mode: 0700

    - name: Run modprobe_modules.sh to harden atm
      shell: |
        bash /root/modprobe_modules.sh atm


#---------------------------------------------------------------------------
